syntax = "proto3";

package HellHeavenInterop;
option csharp_namespace = "DBI.HellHeavenInterop";

message PluginConfiguration {
  repeated PluginConfigurationCategory categories = 1;
}

message PluginConfigurationCategory {
  string name = 1;
  repeated PluginConfigurationEntry entries = 2;
}

message PluginConfigurationEntry {
  string name = 1;
  string description = 2;

  oneof OneOfPluginConfigurationEntry {
    PluginConfigurationBoolEntry boolEntry = 3;
    PluginConfigurationStringEntry stringEntry = 4;
  }
}

message PluginConfigurationBoolEntry {
  bool defaultValue = 3;
}

message PluginConfigurationStringEntry {
  string defaultValue = 3;
  repeated string possibleValues = 4;
}