<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>DBI.Heaven.Launcher</AssemblyName>
        <RootNamespace>DBI.Heaven.Launcher</RootNamespace>
        <Title>Dofus Batteries Included - Heaven Launcher</Title>
        <Product>Heaven Launcher</Product>
        <Authors>Ismail Bennani</Authors>
        <Description>Launcher for Heaven, the Dofus Batteries Included that hosts all the plugins.</Description>
        <PackageProjectUrl>https://github.com/Dofus-Batteries-Included/DBI.Plugins</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Dofus-Batteries-Included/DBI.Plugins</RepositoryUrl>
        <PackageLicense>https://raw.githubusercontent.com/Dofus-Batteries-Included/DBI.Plugins/main/LICENSE</PackageLicense>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <NeutralLanguage>en-US</NeutralLanguage>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IsPackable>false</IsPackable>
        <PublishSingleFile>true</PublishSingleFile>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MinVer" Version="6.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
