<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>DBI.Heaven.Launcher</AssemblyName>
        <RootNamespace>DBI.Heaven.Launcher</RootNamespace>
    </PropertyGroup>

</Project>
