<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>DofusBatteriesIncluded.Plugins.Core</AssemblyName>
        <RootNamespace>DofusBatteriesIncluded.Plugins.Core</RootNamespace>
        <Title>Dofus Batteries Included - Core</Title>
        <Product>DBI.Core</Product>
        <Authors>Ismail Bennani</Authors>
        <Description>Base plugin necessary for all Dofus Batteries Included plugins.</Description>
        <PackageProjectUrl>https://github.com/Dofus-Batteries-Included/DBI.Plugins</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Dofus-Batteries-Included/DBI.Plugins</RepositoryUrl>
        <PackageLicense>https://raw.githubusercontent.com/Dofus-Batteries-Included/DBI.Plugins/main/LICENSE</PackageLicense>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <NeutralLanguage>en-US</NeutralLanguage>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath=""/>
        <None Remove="Protocol\mappings.json" />
        <None Remove="Protocol\game\includes\ui.proto" />
        <None Remove="Protocol\game\includes\treasure_hunt.proto" />
        <None Remove="Protocol\game\includes\taxcollector.proto" />
        <None Remove="Protocol\game\includes\tag_storage.proto" />
        <None Remove="Protocol\game\includes\symbiont.proto" />
        <None Remove="Protocol\game\includes\suggestion.proto" />
        <None Remove="Protocol\game\includes\spell.proto" />
        <None Remove="Protocol\game\includes\social.proto" />
        <None Remove="Protocol\game\includes\server.proto" />
        <None Remove="Protocol\game\includes\security.proto" />
        <None Remove="Protocol\game\includes\script.proto" />
        <None Remove="Protocol\game\includes\roleplay.proto" />
        <None Remove="Protocol\game\includes\quest.proto" />
        <None Remove="Protocol\game\includes\paddock.proto" />
        <None Remove="Protocol\game\includes\npc.proto" />
        <None Remove="Protocol\game\includes\notification.proto" />
        <None Remove="Protocol\game\includes\mount.proto" />
        <None Remove="Protocol\game\includes\moderation.proto" />
        <None Remove="Protocol\game\includes\living_object.proto" />
        <None Remove="Protocol\game\includes\job.proto" />
        <None Remove="Protocol\game\includes\interactive_element.proto" />
        <None Remove="Protocol\game\includes\house.proto" />
        <None Remove="Protocol\game\includes\haven_bag.proto" />
        <None Remove="Protocol\game\includes\haapi.proto" />
        <None Remove="Protocol\game\includes\guild_recruitment.proto" />
        <None Remove="Protocol\game\includes\guild_rank.proto" />
        <None Remove="Protocol\game\includes\guild_member.proto" />
        <None Remove="Protocol\game\includes\guild_information.proto" />
        <None Remove="Protocol\game\includes\guild_house.proto" />
        <None Remove="Protocol\game\includes\guild_application.proto" />
        <None Remove="Protocol\game\includes\gamemap.proto" />
        <None Remove="Protocol\game\includes\game_action.proto" />
        <None Remove="Protocol\game\includes\finish_move.proto" />
        <None Remove="Protocol\game\includes\fight_preparation.proto" />
        <None Remove="Protocol\game\includes\fight.proto" />
        <None Remove="Protocol\game\includes\exchange.proto" />
        <None Remove="Protocol\game\includes\document.proto" />
        <None Remove="Protocol\game\includes\dialog.proto" />
        <None Remove="Protocol\game\includes\debug.proto" />
        <None Remove="Protocol\game\includes\debt.proto" />
        <None Remove="Protocol\game\includes\cosmetic.proto" />
        <None Remove="Protocol\game\includes\context.proto" />
        <None Remove="Protocol\game\includes\contact.proto" />
        <None Remove="Protocol\game\includes\connection.proto" />
        <None Remove="Protocol\game\includes\common.proto" />
        <None Remove="Protocol\game\includes\client_verification.proto" />
        <None Remove="Protocol\game\includes\choice.proto" />
        <None Remove="Protocol\game\includes\chat.proto" />
        <None Remove="Protocol\game\includes\challenge.proto" />
        <None Remove="Protocol\game\includes\bak.proto" />
        <None Remove="Protocol\game\includes\atlas.proto" />
        <None Remove="Protocol\game\includes\area.proto" />
        <None Remove="Protocol\game\includes\appearance.proto" />
        <None Remove="Protocol\game\includes\anomaly.proto" />
        <None Remove="Protocol\game\includes\alteration.proto" />
        <None Remove="Protocol\game\includes\alliance_recruitment.proto" />
        <None Remove="Protocol\game\includes\alliance_member.proto" />
        <None Remove="Protocol\game\includes\alliance_information.proto" />
        <None Remove="Protocol\game\includes\alliance_conquest.proto" />
        <None Remove="Protocol\game\includes\admin_console.proto" />
        <None Remove="Protocol\game\includes\achievement.proto" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
        <PackageReference Include="MinVer" Version="5.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="UnityEngine">
            <HintPath>..\Interop\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\Interop\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
            <HintPath>..\Interop\UnityEngine.UIElementsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>..\Interop\UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="Ankama.AddressableUtility.Runtime">
            <HintPath>..\Interop\Ankama.AddressableUtility.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Core">
            <HintPath>..\Interop\Core.dll</HintPath>
        </Reference>
        <Reference Include="Ankama.Dofus.Protocol.Game">
            <HintPath>..\Interop\Ankama.Dofus.Protocol.Game.dll</HintPath>
        </Reference>
        <Reference Include="Ankama.Dofus.Protocol.Connection">
            <HintPath>..\Interop\Ankama.Dofus.Protocol.Connection.dll</HintPath>
        </Reference>
        <Reference Include="Ankama.Dofus.Core.DataCenter">
            <HintPath>..\Interop\Ankama.Dofus.Core.DataCenter.dll</HintPath>
        </Reference>
        <Reference Include="Ankama.AudioManagement">
            <HintPath>..\Interop\Ankama.AudioManagement.dll</HintPath>
        </Reference>
        <Reference Include="Google.Protobuf">
            <HintPath>..\Interop\Google.Protobuf.dll</HintPath>
        </Reference>
        <Reference Include="Il2Cppmscorlib">
            <HintPath>..\Interop\Il2Cppmscorlib.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Protocol\connection\" />
      <Folder Include="Protocol\game\includes\" />
    </ItemGroup>

    <PropertyGroup>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>
    
</Project>
