using Google.Protobuf;
using HarmonyLib;
using Microsoft.Extensions.Logging;
using MemoryStream = Il2CppSystem.IO.MemoryStream;

namespace DBI.Hell.RedirectMessages;

/// <remarks>
///     The message interceptor has been extracted to a separate assembly so that it can use the proxy version of Google.Protobuf (the one generated by Unhollower) to patch
///     the actual methods used by the game.
///     The rest of Hell uses the actual Google.Protobuf to communicate with Heaven.
/// </remarks>
public class MessageInterceptor
{
    static MessageInterceptor _instance;

    readonly ILogger _logger;

    public MessageInterceptor(ILogger logger)
    {
        _logger = logger;
        _instance = this;

        Harmony.CreateAndPatchAll(typeof(MessageInterceptor));
    }

    public event EventHandler<byte[]> MessageReceived;

    [HarmonyPatch(typeof(MessageParser), nameof(MessageParser.ParseFrom), typeof(CodedInputStream))]
    [HarmonyPostfix]
    static void Postfix(IMessage __result)
    {
        MemoryStream stream = new();
        CodedOutputStream codedOutputStream = new(stream);

        __result.WriteTo(codedOutputStream);
        codedOutputStream.Flush();
        byte[] bytes = stream.ToArray();

        _instance._logger.LogDebug("A message of length {Length} has been received.", bytes.Length);
        _instance.MessageReceived?.Invoke(null, bytes.Take(bytes.Length).ToArray());
    }
}
